---
# Vagrant installation
- name: Check version of installed vagrant
  command: bash -c "dpkg -s vagrant |  awk '/^Version:/ {print substr($2,3)}'"
#  command: dpkg-query -l {{ vagrant.dep_version }}
  register: deb_check
  ignore_errors: yes

# need to test if uninstalling when not installed 1!!!!!!!!!!!!!!
- name: Uninstall other versions of vagrant
  apt:
      name: vagrant
      state: absent
  when: (deb_check.stdout != vagrant.version)
        or
        (deb_check.stdout is none)
        or
        (deb_check.stdout | trim == '')


- name: Downloading vagrant
  become: True
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant.version }}/{{ vagrant.dep_version }}.deb"
    dest: "{{ vagrant.download_destination }}/{{ vagrant.dep_version }}.deb"
  when: deb_check.stdout != vagrant.version


- name : Install vagrant
  become: True
  apt: deb="{{ vagrant.download_destination }}/{{ vagrant.dep_version }}.deb"
  when: deb_check.stdout != vagrant.version
