---

- name: Updade all packages
  become: yes
  apt: update_cache=yes

- name: Install virtualbox
  become: yes
  apt: name=virtualbox-{{version}} state=latest

- name: Install the Python MySQLB module
  become: yes
  apt: name=python-mysqldb state=latest

- name: Template mysql conf file
  become: yes
  template: src=roles/mysql/templates/for-ubuntu-my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0644