---

- name: Add VirtualBox repo key
  apt_key:
    url: "http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc"
    state: present

- name: Add VirtualBox repo
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    state: present
    update_cache: yes

- name: Install virtualbox in given version
  apt:
    name: virtualbox-{{virtualbox.version}}
    state: present

- name: Check if extension pack is already installed
  shell: "VBoxManage list extpacks"
  register: extpack_list

- name: Download VirtualBox extension pack
  shell: "cd /tmp/ &&  wget http://download.virtualbox.org/virtualbox/{{virtualbox.version}}.{{virtualbox.extension_ver}}/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox.version}}.{{virtualbox.extension_ver}}.vbox-extpack"
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: Install VirtualBox extension pack
  shell: "VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox.version}}.{{virtualbox.extension_ver}}.vbox-extpack"
  when: 'extpack_list.stdout == "Extension Packs: 0"'