---
#- name: Updade all packages
#  become: yes
#  apt: update_cache=yes

#- debug:
#    msg: "System {{ virtualbox.version }}"

- name: Install build-esential and dkms (prepare)
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - build-essential
    - dkms
    - unzip

- name: Add VirtualBox repo key
  apt_key:
    url: "http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc"
    state: present
#    when: (ansible_distribution_release == "xenial") or (ansible_distribution_release == "yakkety")

#- name: Add VirtualBox repo key
#  apt_key:
#    url: "http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc"
#    state: present
#    when: not((ansible_distribution_release == "xenial")
#              or
#              (ansible_distribution_release == "yakkety")
#              or
#              (ansible_distribution_release is none)
#              or
#              (ansible_distribution_release | trim == '')
#          )

- name: Add VirtualBox repo
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    state: present
    update_cache: yes

- name: Install virtualbox in given version
  apt:
    name: virtualbox-{{virtualbox.version}}
    state: present

- name: Check if extension pack is already installed
  shell: "VBoxManage list extpacks"
  register: extpack_list

- name: Download VirtualBox extension pack
  shell: "cd /tmp/ &&  wget http://download.virtualbox.org/virtualbox/{{virtualbox.version}}.2/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox.version}}.2.vbox-extpack"
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: Install VirtualBox extension pack
  shell: "VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox.version}}.2.vbox-extpack"
  when: 'extpack_list.stdout == "Extension Packs: 0"'


#- name: Install virtualbox
#  become: yes
#  apt: name=virtualbox-{{ virtualbox.version }} state=latest

#- name: Install the Python MySQLB module
#  become: yes
#  apt: name=python-mysqldb state=latest
#
#- name: Template mysql conf file
#  become: yes
#  template: src=roles/mysql/templates/for-ubuntu-my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0644