---
- name: Install common packets
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
      - build-essential
      - git
#      - libselinux-python
      - software-properties-common
      - mc
      - htop
      - vim
      - nano
      - screen
      - dkms
      - unzip
  ignore_errors: yes

