---
#- name: Add universe repository
#  apt_repository:
#    repo: 'universe'

- name: Install common packets
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    #cache_valid_time=36000
  with_items:
      - build-essential
      - dkms
      - htop
      - git
      - libselinux-python
      - mc
      - nano
      - screen
      - software-properties-common
      - tar
      - unzip
      - vim
  ignore_errors: yes

