---

- name: Add docker repo key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
#    keyserver: keyserver.ubuntu.com
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Add docker repo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
    state: present
    update_cache: yes

- name: Install docker in given version
  apt:
    name: docker
    state: present

#- name: Check if extension pack is already installed
#  shell: "VBoxManage list extpacks"
#  register: extpack_list
#
#- name: Download VirtualBox extension pack
#  shell: "cd /tmp/ &&  wget http://download.virtualbox.org/virtualbox/{{virtualbox.version}}.2/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox.version}}.2.vbox-extpack"
#  when: 'extpack_list.stdout == "Extension Packs: 0"'
#
#- name: Install VirtualBox extension pack
#  shell: "VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox.version}}.2.vbox-extpack"
#  when: 'extpack_list.stdout == "Extension Packs: 0"'